title : Product Performance Analysis
description: This project is about investigating the performance of marketing campaigns at VeraCare Health in order to surface recommendations on marketing budget allocation across future campaign categories.
theme: jekyll-theme-minimal
